### PR TITLE
Refactorings

### PR DESCRIPTION
**Pull request by cconklin**
1. refactored `ControlCluster.control`
2. I modified the internal implementation of how masks are generated, though the result should remain the same. I'm not sure how this will affect sensors. If you want to go forward with this, the split `manage_light` methods can be removed from the API.

### CODE REVIEW

**Comment by cconklin** [comment]
@jeffrobots 

I can split the commits if you don't want to merge the mask code change.

**Comment by jeffrobots** [comment]
I have a possible solution. 

A class method that iterates through all of the available control objects and creates a master mask before updating the IO expander much like what I've done with the sensor modules would be a decently elegant way of keeping instance masks separate so that they can update dynamically while at the same time giving the class knowledge of what each instance is doing so that nothing conflicts.

It will also solve the problem of needing to handle the pump specially for ID 3 and 4.

**Comment by jeffrobots** [comment]
@cconklin 
I noticed another issue with the way the pump is handled which more or less is a reflection of the problem with IDs 3 and 4.

Since the instances each contain their own mask, it wouldn't be possible for anything outside of bank 0 to toggle the pump pin on. This is why I was using the list pump_operation.

I have a possible solution that I'm going to try out. Basically, I want to use a class method that updates a master mask for both banks by iterating through the ControlCluster instances much like what I do in the SensorCluster module. This means I'd be removing: 

``` python
        if self.bank == 0 and self.controls["pump"] == "on":
            mask |= 1 << ControlCluster.pump_pin
```

and instead saying

``` python
    if self.controls["pump"] == "on":
        ControlCluster.pump_operation[self.ID-1] = 1
```

I would then use the classmethod to check the contents of the pump_operation list and fill in the corresponding pump mask bit accordingly. This same class method would also iterate over the available control objects and combine their respective masks into something the IO expander can use.

Overall, it's reverting a bit back to how I was taking care of things before. It's just more dynamic due to the mask property and a bit more pythonic. I also get to make ControlCluster iterable, which could come in handy later on anyway.

Any thoughts on that?

On second thought, I don't even need to use a pump_operation list. I can just have a variable in each instance to hold whether or not it wants the pump on or not and iterate over the objects checking this variable.

**Comment by jeffrobots** [comment]
@cconklin 

If you're fine with my recent changes, this branch can be merged into the master. It seems to be working great.

**Pull request merged**
